name: Playwright Tests
on:
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
jobs: null
test:
  runs-on: ubuntu-latest
  permissions:
    contents: write
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Run Playwright tests
      run: npm run test
    - name: Upload Allure artifact
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: test-results
        path: test-results
        retention-days: 3
    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Generate Allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 10
    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        publish_dir: allure-history
        publish_branch: gh-pages
